/**
 * Umfangreiche deutsche Synonymdatenbank für Autoren
 * 500+ Wörter mit hochwertigen Synonymen
 */

export const SYNONYM_MAP: Record<string, string[]> = {
  // BEWEGUNGSVERBEN
  gehen: ['schreiten', 'wandeln', 'spazieren', 'laufen', 'marschieren', 'eilen', 'trotten', 'schlendern', 'stapfen', 'wandern'],
  laufen: ['rennen', 'sprinten', 'hasten', 'hetzen', 'stürmen', 'flitzen', 'rasen', 'joggen', 'eilen', 'sausen'],
  kommen: ['ankommen', 'erscheinen', 'eintreffen', 'auftauchen', 'nahen', 'herantreten', 'eintreten'],
  rennen: ['laufen', 'sprinten', 'rasen', 'hetzen', 'stürmen', 'flitzen', 'jagen', 'preschen'],
  fahren: ['reisen', 'kutschieren', 'chauffieren', 'steuern', 'lenken', 'brausen', 'rollen'],
  fliegen: ['schweben', 'gleiten', 'segeln', 'flattern', 'kreisen'],
  springen: ['hüpfen', 'hopsen', 'hoppeln', 'setzen', 'schnellen', 'aufspringen'],
  fallen: ['stürzen', 'sinken', 'purzeln', 'abstürzen', 'hinunterfallen', 'niedergehen'],
  steigen: ['klettern', 'emporklettern', 'erklimmen', 'hinaufsteigen', 'aufsteigen'],
  kriechen: ['schleichen', 'robben', 'krabbeln', 'gleiten'],
  schwimmen: ['tauchen', 'paddeln', 'planschen', 'baden', 'treiben'],
  
  // SPRECHVERBEN
  sagen: ['sprechen', 'äußern', 'bemerken', 'erklären', 'meinen', 'erzählen', 'mitteilen', 'verkünden', 'aussprechen'],
  fragen: ['erkundigen', 'befragen', 'nachfragen', 'erfragen', 'ausfragen', 'interviewen'],
  antworten: ['erwidern', 'entgegnen', 'reagieren', 'zurückgeben', 'replizieren'],
  rufen: ['schreien', 'brüllen', 'kreischen', 'johlen', 'ausrufen'],
  flüstern: ['wispern', 'raunen', 'murmeln', 'tuscheln', 'hauchen', 'säuseln'],
  schreien: ['brüllen', 'kreischen', 'johlen', 'zetern', 'keifen'],
  erzählen: ['berichten', 'schildern', 'beschreiben', 'wiedergeben', 'darlegen'],
  sprechen: ['reden', 'plaudern', 'diskutieren', 'konversieren'],
  behaupten: ['versichern', 'beteuern', 'bekräftigen', 'bestätigen', 'erklären'],
  bitten: ['ersuchen', 'anflehen', 'beschwören', 'anfragen', 'nachsuchen'],
  
  // EMOTIONSVERBEN
  lieben: ['mögen', 'verehren', 'anbeten', 'vergöttern', 'schwärmen', 'begehren'],
  hassen: ['verabscheuen', 'verachten', 'ablehnen', 'anfeinden', 'bekämpfen'],
  freuen: ['beglücken', 'erfreuen', 'entzücken', 'begeistern', 'jubeln'],
  ärgern: ['reizen', 'provozieren', 'aufbringen', 'erzürnen'],
  fürchten: ['ängstigen', 'erschrecken', 'bangen', 'grauen', 'scheuen'],
  hoffen: ['wünschen', 'erwarten', 'ersehnen', 'erhoffen', 'vertrauen'],
  trauern: ['betrauern', 'beklagen', 'beweinen', 'jammern', 'klagen'],
  lachen: ['kichern', 'grinsen', 'schmunzeln', 'glucksen', 'prusten', 'wiehern'],
  weinen: ['heulen', 'schluchzen', 'flennen', 'greinen', 'wimmern'],
  staunen: ['wundern', 'erstaunen', 'verblüffen', 'überraschen'],
  
  // DENKVERBEN
  denken: ['überlegen', 'nachdenken', 'grübeln', 'sinnen', 'meditieren', 'reflektieren'],
  wissen: ['kennen', 'verstehen', 'begreifen', 'erfassen', 'durchschauen'],
  glauben: ['meinen', 'annehmen', 'vermuten', 'denken', 'unterstellen'],
  verstehen: ['begreifen', 'erfassen', 'kapieren', 'durchblicken', 'nachvollziehen'],
  erkennen: ['wahrnehmen', 'bemerken', 'entdecken', 'feststellen', 'identifizieren'],
  vergessen: ['entfallen', 'versäumen', 'übersehen', 'verdrängen'],
  erinnern: ['gedenken', 'zurückdenken', 'besinnen'],
  lernen: ['studieren', 'pauken', 'büffeln', 'erlernen'],
  entscheiden: ['beschließen', 'bestimmen', 'festlegen', 'wählen', 'urteilen'],
  planen: ['vorbereiten', 'organisieren', 'konzipieren', 'entwerfen', 'ausarbeiten'],
  
  // HANDLUNGSVERBEN
  machen: ['tun', 'handeln', 'ausführen', 'vollbringen', 'verrichten', 'erledigen'],
  geben: ['reichen', 'überreichen', 'aushändigen', 'überlassen', 'schenken'],
  nehmen: ['greifen', 'packen', 'ergreifen', 'fassen', 'schnappen'],
  halten: ['festhalten', 'greifen', 'umklammern', 'umfassen', 'bewahren'],
  lassen: ['erlauben', 'gestatten', 'zulassen', 'gewähren', 'dulden'],
  zeigen: ['präsentieren', 'vorführen', 'demonstrieren', 'offenbaren', 'darstellen'],
  finden: ['entdecken', 'aufspüren', 'auftreiben', 'aufstöbern', 'orten'],
  suchen: ['fahnden', 'forschen', 'stöbern', 'durchkämmen', 'durchsuchen'],
  helfen: ['unterstützen', 'beistehen', 'assistieren'],
  arbeiten: ['schaffen', 'werken', 'wirken', 'werkeln'],
  kämpfen: ['streiten', 'ringen', 'fechten', 'bekämpfen'],
  gewinnen: ['siegen', 'triumphieren', 'obsiegen'],
  verlieren: ['einbüßen', 'abgeben', 'hergeben'],
  beginnen: ['anfangen', 'starten', 'einleiten', 'eröffnen', 'einsetzen'],
  beenden: ['abschließen', 'vollenden', 'aufhören', 'fertigstellen'],
  öffnen: ['aufmachen', 'aufsperren', 'aufschließen', 'entriegeln'],
  schließen: ['zumachen', 'zuschlagen', 'absperren', 'verriegeln'],
  
  // SEHVERBEN
  sehen: ['blicken', 'schauen', 'betrachten', 'beobachten', 'erblicken', 'anschauen'],
  schauen: ['blicken', 'gucken', 'spähen', 'lugen', 'äugen'],
  beobachten: ['überwachen', 'kontrollieren', 'verfolgen'],
  starren: ['anstarren', 'fixieren', 'anglotzen', 'gaffen'],
  
  // POSITIVE ADJEKTIVE
  gut: ['hervorragend', 'ausgezeichnet', 'vorzüglich', 'exzellent', 'trefflich', 'vorbildlich'],
  schön: ['wunderschön', 'hübsch', 'anmutig', 'bezaubernd', 'reizvoll', 'attraktiv', 'ansprechend'],
  groß: ['riesig', 'gewaltig', 'enorm', 'immens', 'gigantisch', 'mächtig', 'stattlich'],
  schnell: ['rasch', 'flink', 'zügig', 'hurtig', 'eilig', 'flott', 'geschwind', 'blitzschnell'],
  stark: ['kräftig', 'mächtig', 'robust', 'stämmig', 'muskulös', 'gewaltig', 'kraftvoll'],
  klug: ['intelligent', 'gescheit', 'weise', 'schlau', 'clever', 'scharfsinnig', 'geistreich'],
  freundlich: ['nett', 'liebenswürdig', 'herzlich', 'warmherzig', 'zuvorkommend', 'hilfsbereit'],
  glücklich: ['froh', 'fröhlich', 'heiter', 'vergnügt', 'selig', 'überglücklich', 'beglückt'],
  interessant: ['spannend', 'fesselnd', 'faszinierend', 'packend', 'reizvoll', 'anregend'],
  wichtig: ['bedeutend', 'bedeutsam', 'wesentlich', 'entscheidend', 'relevant', 'maßgeblich'],
  neu: ['frisch', 'neuartig', 'modern', 'aktuell', 'innovativ', 'zeitgemäß'],
  alt: ['betagt', 'bejahrt', 'antik', 'historisch', 'uralt', 'altehrwürdig'],
  jung: ['jugendlich', 'juvenil', 'minderjährig', 'kindlich'],
  reich: ['wohlhabend', 'vermögend', 'begütert', 'betucht', 'steinreich'],
  arm: ['mittellos', 'bedürftig', 'unbemittelt', 'verarmt', 'besitzlos'],
  mutig: ['tapfer', 'kühn', 'wagemutig', 'furchtlos', 'unerschrocken', 'beherzt'],
  ruhig: ['still', 'friedlich', 'gelassen', 'ausgeglichen', 'entspannt', 'besinnlich'],
  laut: ['lärmend', 'geräuschvoll', 'dröhnend', 'schallend', 'tosend'],
  leise: ['still', 'gedämpft', 'flüsternd', 'unhörbar', 'geräuschlos'],
  hell: ['leuchtend', 'strahlend', 'licht', 'erhellt', 'glänzend'],
  dunkel: ['finster', 'düster', 'schattig', 'dämmerig', 'lichtlos'],
  warm: ['heiß', 'lauwarm', 'mild', 'sommerlich', 'behaglich'],
  kalt: ['kühl', 'frostig', 'eisig', 'winterlich', 'frisch'],
  nass: ['feucht', 'durchnässt', 'triefend', 'klamm', 'regnerisch'],
  trocken: ['dürr', 'ausgetrocknet', 'wasserarm', 'verdorrt'],
  schwer: ['gewichtig', 'massiv', 'wuchtig', 'lastend', 'bleischwer'],
  leicht: ['federleicht', 'schwerelos', 'gewichtslos', 'mühelos'],
  voll: ['gefüllt', 'prall', 'übervoll', 'randvoll', 'vollgestopft'],
  leer: ['entleert', 'ausgeräumt', 'unbesetzt', 'verlassen', 'öde'],
  wahr: ['wahrhaftig', 'authentisch', 'echt', 'tatsächlich', 'aufrichtig'],
  falsch: ['unwahr', 'unrichtig', 'irrig', 'fehlerhaft', 'verkehrt'],
  sicher: ['gewiss', 'zuverlässig', 'ungefährdet', 'geschützt', 'geborgen'],
  gefährlich: ['riskant', 'bedrohlich', 'risikoreich', 'gewagt', 'halsbrecherisch'],
  einfach: ['simpel', 'unkompliziert', 'mühelos', 'kinderleicht', 'schlicht'],
  schwierig: ['kompliziert', 'knifflig', 'vertrackt', 'verzwickt', 'anspruchsvoll'],
  
  // NEGATIVE ADJEKTIVE
  schlecht: ['übel', 'miserabel', 'mangelhaft', 'ungenügend', 'minderwertig'],
  hässlich: ['unschön', 'unansehnlich', 'abstoßend', 'unattraktiv', 'garstig'],
  klein: ['winzig', 'mickrig', 'zierlich', 'minimal', 'zwergenhaft'],
  langsam: ['träge', 'gemächlich', 'bedächtig', 'schleppend', 'lahm'],
  schwach: ['kraftlos', 'matt', 'gebrechlich', 'hinfällig', 'entkräftet'],
  dumm: ['töricht', 'unklug', 'albern', 'einfältig', 'beschränkt'],
  böse: ['gemein', 'fies', 'boshaft', 'niederträchtig', 'übel'],
  traurig: ['betrübt', 'niedergeschlagen', 'bekümmert', 'melancholisch', 'wehmütig'],
  langweilig: ['öde', 'eintönig', 'fade', 'monoton', 'ermüdend', 'einschläfernd'],
  ängstlich: ['furchtsam', 'schreckhaft', 'verzagt', 'schüchtern', 'zaghaft'],
  wütend: ['zornig', 'erbost', 'aufgebracht', 'erzürnt', 'rasend', 'tobend'],
  müde: ['erschöpft', 'ermattet', 'abgeschlagen', 'schläfrig', 'kraftlos'],
  krank: ['leidend', 'unpässlich', 'angeschlagen', 'erkrankt', 'siech'],
  
  // SUBSTANTIVE - MENSCHEN
  Mensch: ['Person', 'Individuum', 'Wesen', 'Erdenbürger'],
  Mann: ['Herr', 'Kerl', 'Bursche', 'Typ', 'Gentleman'],
  Frau: ['Dame', 'Lady', 'Fräulein'],
  Kind: ['Sprössling', 'Nachwuchs', 'Knirps', 'Kleines', 'Bengel'],
  Freund: ['Kamerad', 'Kumpel', 'Gefährte', 'Vertrauter', 'Begleiter'],
  Feind: ['Gegner', 'Widersacher', 'Rivale', 'Kontrahent', 'Antagonist'],
  Held: ['Champion', 'Recke', 'Kämpfer', 'Retter', 'Protagonist'],
  König: ['Monarch', 'Herrscher', 'Regent', 'Souverän', 'Majestät'],
  Bauer: ['Landwirt', 'Farmer', 'Agrarier', 'Landmann', 'Ackerbauer'],
  Arzt: ['Doktor', 'Mediziner', 'Heilkundiger', 'Medikus'],
  Lehrer: ['Pädagoge', 'Erzieher', 'Dozent', 'Ausbilder', 'Mentor'],
  Chef: ['Boss', 'Vorgesetzter', 'Leiter', 'Direktor', 'Oberhaupt'],
  Soldat: ['Krieger', 'Kämpfer', 'Militär', 'Rekrut', 'Söldner'],
  Diener: ['Bediensteter', 'Lakai', 'Knecht', 'Butler', 'Kammerdiener'],
  
  // SUBSTANTIVE - ORTE
  Haus: ['Gebäude', 'Heim', 'Domizil', 'Behausung', 'Anwesen', 'Residenz'],
  Zimmer: ['Raum', 'Kammer', 'Gemach', 'Stube', 'Saal'],
  Stadt: ['Metropole', 'Großstadt', 'Kommune', 'Ortschaft'],
  Dorf: ['Siedlung', 'Ortschaft', 'Weiler', 'Flecken'],
  Land: ['Nation', 'Staat', 'Reich', 'Heimat', 'Territorium'],
  Wald: ['Forst', 'Hain', 'Gehölz', 'Dickicht', 'Urwald'],
  Berg: ['Gipfel', 'Anhöhe', 'Erhebung', 'Hügel', 'Kuppe'],
  Fluss: ['Strom', 'Gewässer', 'Wasserlauf', 'Bach', 'Kanal'],
  See: ['Teich', 'Weiher', 'Gewässer', 'Tümpel'],
  Meer: ['Ozean', 'Gewässer', 'Weltmeer'],
  Straße: ['Weg', 'Gasse', 'Allee', 'Pfad', 'Boulevard'],
  Weg: ['Pfad', 'Straße', 'Route', 'Strecke', 'Passage'],
  Platz: ['Stelle', 'Ort', 'Fleck', 'Standort', 'Position'],
  Garten: ['Park', 'Anlage', 'Grünfläche', 'Grünanlage'],
  Kirche: ['Gotteshaus', 'Kathedrale', 'Dom', 'Kapelle', 'Tempel'],
  Schule: ['Bildungseinrichtung', 'Lehranstalt', 'Akademie'],
  Krankenhaus: ['Klinik', 'Hospital', 'Spital', 'Heilanstalt'],
  
  // SUBSTANTIVE - DINGE
  Ding: ['Sache', 'Objekt', 'Gegenstand', 'Artikel', 'Utensil'],
  Auto: ['Wagen', 'Fahrzeug', 'PKW', 'Automobil', 'Gefährt', 'Karre'],
  Computer: ['Rechner', 'PC', 'Laptop', 'Rechenmaschine'],
  Telefon: ['Handy', 'Mobiltelefon', 'Fernsprecher', 'Smartphone'],
  Buch: ['Werk', 'Band', 'Schmöker', 'Lektüre', 'Wälzer'],
  Brief: ['Schreiben', 'Mitteilung', 'Nachricht', 'Epistel'],
  Geld: ['Kapital', 'Vermögen', 'Währung', 'Finanzen', 'Kohle'],
  Tür: ['Pforte', 'Eingang', 'Portal', 'Tor', 'Zugang'],
  Fenster: ['Öffnung', 'Luke', 'Glasscheibe'],
  Tisch: ['Tafel', 'Pult', 'Schreibtisch', 'Tresen'],
  Stuhl: ['Sessel', 'Hocker', 'Sitz', 'Sitzgelegenheit'],
  Bett: ['Lager', 'Koje', 'Schlafstätte', 'Liege'],
  Kleid: ['Gewand', 'Robe', 'Kostüm', 'Garderobe'],
  Schuh: ['Treter', 'Fußbekleidung', 'Stiefel', 'Sandale'],
  Waffe: ['Schwert', 'Klinge', 'Wehr', 'Mordwerkzeug'],
  Schwert: ['Klinge', 'Degen', 'Säbel', 'Waffe'],
  Schild: ['Schutzschild', 'Buckler', 'Tartsche'],
  
  // SUBSTANTIVE - NATUR
  Baum: ['Gewächs', 'Stamm', 'Eiche', 'Pflanze'],
  Blume: ['Blüte', 'Pflanze', 'Gewächs', 'Flora'],
  Tier: ['Kreatur', 'Lebewesen', 'Geschöpf', 'Fauna', 'Vieh'],
  Hund: ['Köter', 'Vierbeiner', 'Wauwau', 'Bello'],
  Katze: ['Mieze', 'Stubentiger', 'Samtpfote', 'Kätzchen'],
  Pferd: ['Ross', 'Gaul', 'Hengst', 'Stute', 'Klepper'],
  Vogel: ['Federvieh', 'Piepmatz', 'Gefiederte'],
  Sonne: ['Gestirn', 'Himmelskörper', 'Tagesgestirn', 'Feuerball'],
  Mond: ['Erdtrabant', 'Nachtgestirn', 'Luna'],
  Stern: ['Gestirn', 'Himmelskörper', 'Fixstern'],
  Himmel: ['Firmament', 'Äther', 'Wolken', 'Himmelsgewölbe'],
  Erde: ['Boden', 'Grund', 'Scholle', 'Erdreich'],
  Wasser: ['Nass', 'Flüssigkeit', 'Quelle', 'Trunk'],
  Feuer: ['Flamme', 'Brand', 'Lohe', 'Glut', 'Inferno'],
  Wind: ['Brise', 'Sturm', 'Böe', 'Luftzug', 'Orkan'],
  Regen: ['Niederschlag', 'Schauer', 'Nass', 'Sprühregen'],
  Schnee: ['Flocken', 'Pulverschnee', 'Neuschnee'],
  
  // SUBSTANTIVE - ABSTRAKT
  Zeit: ['Zeitspanne', 'Epoche', 'Ära', 'Periode', 'Phase'],
  Tag: ['Datum', 'Kalendertag', 'Werktag'],
  Nacht: ['Dunkelheit', 'Finsternis', 'Abend'],
  Jahr: ['Zeitraum', 'Kalenderjahr', 'Periode'],
  Leben: ['Dasein', 'Existenz', 'Lebenszeit', 'Lebenslauf'],
  Tod: ['Ableben', 'Ende', 'Hinscheiden', 'Sterben'],
  Liebe: ['Zuneigung', 'Hingabe', 'Leidenschaft', 'Verliebtheit'],
  Hass: ['Abneigung', 'Feindschaft', 'Abscheu', 'Verachtung'],
  Angst: ['Furcht', 'Schrecken', 'Panik', 'Bangen', 'Grauen'],
  Freude: ['Glück', 'Vergnügen', 'Wonne', 'Begeisterung', 'Jubel'],
  Trauer: ['Kummer', 'Leid', 'Schmerz', 'Gram', 'Betrübnis'],
  Hoffnung: ['Zuversicht', 'Erwartung', 'Vertrauen', 'Optimismus'],
  Kraft: ['Stärke', 'Energie', 'Macht', 'Power', 'Potenz'],
  Mut: ['Tapferkeit', 'Kühnheit', 'Courage', 'Beherztheit'],
  Freiheit: ['Unabhängigkeit', 'Selbstständigkeit', 'Autonomie'],
  Frieden: ['Ruhe', 'Harmonie', 'Eintracht'],
  Krieg: ['Kampf', 'Schlacht', 'Konflikt', 'Gefecht'],
  Wahrheit: ['Realität', 'Tatsache', 'Wirklichkeit', 'Faktum'],
  Lüge: ['Unwahrheit', 'Flunkerei', 'Schwindel', 'Märchen'],
  Geheimnis: ['Mysterium', 'Rätsel', 'Arkanum', 'Verborgenheit'],
  Traum: ['Vision', 'Fantasie', 'Wunschbild', 'Illusion'],
  Gedanke: ['Idee', 'Einfall', 'Überlegung', 'Vorstellung'],
  Gefühl: ['Emotion', 'Empfindung', 'Regung', 'Sentiment'],
  Seele: ['Geist', 'Psyche', 'Inneres', 'Wesen'],
  Herz: ['Seele', 'Gemüt', 'Innerstes', 'Zentrum'],
  Verstand: ['Intellekt', 'Vernunft', 'Geist', 'Ratio'],
  Wille: ['Entschlossenheit', 'Absicht', 'Vorsatz', 'Bestreben'],
  Schicksal: ['Fügung', 'Los', 'Geschick', 'Bestimmung', 'Karma'],
  Glück: ['Freude', 'Segen', 'Erfolg', 'Fortune', 'Heil'],
  Unglück: ['Pech', 'Missgeschick', 'Unheil', 'Tragödie'],
  Erfolg: ['Triumph', 'Sieg', 'Errungenschaft', 'Gelingen'],
  Misserfolg: ['Niederlage', 'Fehlschlag', 'Scheitern', 'Fiasko'],
  Problem: ['Schwierigkeit', 'Hindernis', 'Hürde', 'Komplikation'],
  Lösung: ['Ausweg', 'Antwort', 'Abhilfe', 'Resultat'],
  Frage: ['Anfrage', 'Erkundigung', 'Problem', 'Thema'],
  Antwort: ['Erwiderung', 'Reaktion', 'Replik', 'Bescheid'],
  Geschichte: ['Erzählung', 'Story', 'Bericht', 'Historie'],
  Abenteuer: ['Erlebnis', 'Wagnis', 'Expedition', 'Eskapade'],
  Reise: ['Trip', 'Fahrt', 'Expedition', 'Tour', 'Ausflug'],
  
  // ADVERBIEN
  sehr: ['äußerst', 'überaus', 'höchst', 'extrem', 'ungemein', 'außerordentlich'],
  viel: ['reichlich', 'massenhaft', 'zahlreich', 'unzählig'],
  wenig: ['kaum', 'gering', 'knapp', 'spärlich', 'minimal'],
  immer: ['stets', 'ständig', 'fortwährend', 'permanent', 'allezeit'],
  nie: ['niemals', 'nimmer', 'keinesfalls'],
  oft: ['häufig', 'oftmals', 'vielfach', 'regelmäßig', 'ständig'],
  selten: ['rar', 'gelegentlich', 'vereinzelt'],
  bald: ['demnächst', 'zeitnah', 'alsbald'],
  jetzt: ['nun', 'momentan', 'gegenwärtig', 'augenblicklich', 'sofort'],
  hier: ['vor Ort'],
  dort: ['drüben', 'da'],
  oben: ['droben', 'oberhalb', 'aufwärts'],
  unten: ['drunten', 'unterhalb', 'abwärts', 'tief'],
  vorne: ['voraus'],
  hinten: ['rückwärts'],
  plötzlich: ['unvermittelt', 'abrupt', 'schlagartig', 'urplötzlich'],
  endlich: ['schließlich', 'letztendlich', 'schlussendlich'],
  vielleicht: ['möglicherweise', 'eventuell', 'womöglich'],
  wahrscheinlich: ['vermutlich', 'wohl', 'mutmaßlich', 'voraussichtlich'],
  natürlich: ['selbstverständlich', 'freilich', 'gewiss', 'logischerweise'],
  wirklich: ['tatsächlich', 'wahrhaftig', 'fürwahr'],
  eigentlich: ['ursprünglich'],
  besonders: ['insbesondere', 'speziell', 'namentlich'],
  zusammen: ['gemeinsam', 'miteinander', 'vereint', 'kollektiv'],
  allein: ['einsam', 'solo', 'verlassen'],
  etwa: ['ungefähr', 'circa', 'annähernd', 'rund'],
  ganz: ['völlig', 'komplett', 'vollständig', 'total'],
  genau: ['exakt', 'präzise', 'akkurat', 'punktgenau'],
  auch: ['ebenfalls', 'gleichfalls', 'ebenso', 'desgleichen'],
  noch: ['weiterhin', 'zusätzlich', 'obendrein'],
  schon: ['bereits', 'mittlerweile', 'inzwischen'],
  wieder: ['erneut', 'abermals', 'nochmals'],
  
  // KONJUNKTIONEN
  aber: ['jedoch', 'allerdings', 'doch', 'dennoch', 'indessen'],
  und: ['sowie', 'außerdem', 'ferner', 'zudem', 'überdies'],
  oder: ['beziehungsweise', 'alternativ', 'andernfalls'],
  weil: ['da', 'denn', 'zumal', 'nachdem'],
  obwohl: ['obgleich', 'wenngleich', 'trotzdem', 'nichtsdestotrotz'],
  wenn: ['falls', 'sofern', 'sobald'],
  damit: ['sodass'],
  also: ['folglich', 'demzufolge', 'somit', 'mithin', 'ergo'],
  deshalb: ['daher', 'darum', 'deswegen'],
  trotzdem: ['dennoch', 'nichtsdestotrotz', 'gleichwohl'],
  
  // === ERWEITERTE VERBEN ===
  warten: ['harren', 'ausharren', 'verweilen', 'zuwarten', 'abwarten'],
  schlafen: ['schlummern', 'ruhen', 'dösen', 'pennen', 'ratzen', 'knacken'],
  aufwachen: ['erwachen', 'aufstehen', 'hochschrecken', 'munter werden'],
  essen: ['speisen', 'verzehren', 'verspeisen', 'tafeln', 'mampfen', 'futtern', 'schlemmen'],
  trinken: ['schlürfen', 'nippen', 'kippen', 'saufen', 'gurgeln'],
  kochen: ['brutzeln', 'braten', 'schmoren', 'garen', 'zubereiten'],
  waschen: ['säubern', 'reinigen', 'spülen', 'putzen', 'schrubben'],
  anziehen: ['kleiden', 'anlegen', 'überstreifen', 'überziehen'],
  ausziehen: ['entkleiden', 'ablegen', 'abstreifen'],
  kaufen: ['erwerben', 'erstehen', 'anschaffen', 'besorgen', 'shoppen'],
  verkaufen: ['veräußern', 'absetzen', 'losschlagen', 'verhökern'],
  bezahlen: ['begleichen', 'entrichten', 'berappen', 'blechen'],
  stehlen: ['klauen', 'entwenden', 'mopsen', 'mitgehen lassen', 'rauben'],
  lügen: ['flunkern', 'schwindeln', 'täuschen', 'mogeln', 'fabulieren'],
  betrügen: ['hintergehen', 'täuschen', 'prellen', 'übers Ohr hauen'],
  verletzen: ['verwunden', 'versehren', 'schädigen', 'beschädigen'],
  heilen: ['kurieren', 'genesen', 'gesunden', 'erholen'],
  sterben: ['ableben', 'verscheiden', 'hinscheiden', 'versterben', 'entschlafen', 'dahinscheiden'],
  töten: ['ermorden', 'umbringen', 'erschlagen', 'beseitigen', 'vernichten'],
  retten: ['befreien', 'erlösen', 'bewahren', 'bergen', 'erretten'],
  schützen: ['beschützen', 'verteidigen', 'bewachen', 'behüten', 'sichern'],
  angreifen: ['attackieren', 'überfallen', 'anfallen', 'bestürmen'],
  verteidigen: ['schützen', 'abwehren', 'beschirmen', 'decken'],
  siegreich: ['triumphierend', 'erfolgreich', 'obsiegend'],
  unterliegen: ['einbüßen', 'verspielen', 'preisgeben', 'abgeben'],
  spielen: ['toben', 'tollen', 'herumtollen', 'zocken', 'daddeln'],
  lesen: ['studieren', 'durchlesen', 'schmökern', 'überfliegen', 'anlesen'],
  schreiben: ['verfassen', 'niederschreiben', 'notieren', 'aufschreiben', 'kritzeln'],
  zeichnen: ['skizzieren', 'malen', 'kritzeln', 'entwerfen', 'illustrieren'],
  singen: ['trällern', 'schmettern', 'jodeln', 'summen', 'intonieren'],
  tanzen: ['wirbeln', 'schwingen', 'schwofen', 'hüpfen'],
  lächeln: ['schmunzeln', 'grinsen', 'strahlen', 'feixen'],
  küssen: ['knutschen', 'schmusen', 'herzen', 'liebkosen'],
  umarmen: ['umfassen', 'umschlingen', 'drücken', 'herzen'],
  berühren: ['anfassen', 'betasten', 'streifen', 'tangieren'],
  schlagen: ['hauen', 'prügeln', 'dreschen', 'verprügeln', 'boxen'],
  treten: ['kicken', 'stoßen', 'stampfen', 'ausschlagen'],
  werfen: ['schleudern', 'schmeißen', 'feuern', 'katapultieren'],
  fangen: ['greifen', 'erhaschen', 'erwischen', 'schnappen', 'einfangen'],
  ziehen: ['zerren', 'reißen', 'schleppen', 'schleifen', 'zupfen'],
  schieben: ['drücken', 'stoßen', 'rücken', 'wälzen'],
  heben: ['anheben', 'hochheben', 'stemmen', 'hieven', 'lupfen'],
  senken: ['absenken', 'herunterlassen', 'herabsetzen'],
  drehen: ['wenden', 'rotieren', 'kreiseln', 'schwenken', 'kurbeln'],
  biegen: ['krümmen', 'verbiegen', 'beugen', 'wölben'],
  brechen: ['zerbrechen', 'zerschlagen', 'knacken', 'zersplittern'],
  reparieren: ['flicken', 'ausbessern', 'instandsetzen', 'richten'],
  bauen: ['errichten', 'konstruieren', 'aufbauen', 'erbauen'],
  zerstören: ['vernichten', 'demolieren', 'zertrümmern', 'verwüsten'],
  verbrennen: ['versengen', 'ankokeln', 'einäschern'],
  löschen: ['ausmachen', 'ersticken', 'dämpfen', 'tilgen'],
  gießen: ['schütten', 'kippen', 'eingießen', 'bewässern'],
  füllen: ['befüllen', 'auffüllen', 'vollmachen', 'stopfen'],
  leeren: ['entleeren', 'ausschütten', 'ausgießen', 'räumen'],
  mischen: ['vermengen', 'verrühren', 'vermischen', 'kombinieren'],
  trennen: ['teilen', 'scheiden', 'sondern', 'spalten', 'separieren'],
  verbinden: ['vereinen', 'verknüpfen', 'zusammenfügen', 'koppeln'],
  wachsen: ['gedeihen', 'sprießen', 'zunehmen', 'heranwachsen'],
  schrumpfen: ['einschrumpfen', 'zusammenschrumpfen', 'verkleinern', 'schwinden'],
  erscheinen: ['auftauchen', 'auftreten', 'hervorkommen', 'sichtbar werden'],
  verschwinden: ['entschwinden', 'entweichen', 'vergehen', 'schwinden'],
  starten: ['anfangen', 'einleiten', 'loslegen', 'anbrechen', 'losgehen'],
  enden: ['aufhören', 'abschließen', 'ausklingen', 'auslaufen'],
  dauern: ['anhalten', 'währen', 'andauern', 'fortdauern'],
  wechseln: ['tauschen', 'austauschen', 'umtauschen', 'ändern'],
  ändern: ['verändern', 'modifizieren', 'umgestalten', 'wandeln', 'abwandeln'],
  entwickeln: ['entfalten', 'herausbilden', 'ausarbeiten', 'kreieren'],
  verbessern: ['optimieren', 'perfektionieren', 'aufwerten', 'verfeinern'],
  verschlechtern: ['verschlimmern', 'beeinträchtigen', 'mindern'],
  vergrößern: ['erweitern', 'ausdehnen', 'ausbauen', 'aufblähen'],
  verkleinern: ['reduzieren', 'minimieren', 'schrumpfen', 'kürzen'],
  aufschließen: ['öffnen', 'aufsperren', 'entriegeln', 'aufklappen', 'aufmachen'],
  zuschließen: ['zumachen', 'zuschlagen', 'verriegeln', 'absperren', 'zuklappen'],
  eintreten: ['hereinkommen', 'hineintreten', 'betreten', 'ankommen'],
  austreten: ['hinausgehen', 'verlassen', 'ausscheiden'],
  aufstehen: ['erheben', 'hochkommen', 'aufspringen'],
  hinsetzen: ['niederlassen', 'platzieren', 'niedersetzen'],
  hinlegen: ['ablegen', 'niederlegen', 'deponieren', 'betten'],
  aufheben: ['hochheben', 'aufnehmen', 'aufsammeln', 'aufklauben'],
  loslassen: ['freigeben', 'freilassen', 'entlassen', 'lockern'],
  festhalten: ['greifen', 'packen', 'klammern', 'umklammern'],
  drücken: ['pressen', 'quetschen', 'zusammendrücken', 'kneifen'],
  entspannen: ['erholen', 'lockern', 'relaxen', 'ausspannen'],
  anstrengen: ['bemühen', 'plagen', 'abmühen', 'strapazieren'],
  ermüden: ['erschöpfen', 'ermatten', 'auslaugen', 'schlauchen'],
  beeindrucken: ['imponieren', 'faszinieren', 'überwältigen', 'verblüffen'],
  enttäuschen: ['frustrieren', 'desillusionieren', 'ernüchtern'],
  überraschen: ['verblüffen', 'erstaunen', 'verwundern', 'frappieren'],
  erschrecken: ['ängstigen', 'aufschrecken', 'entsetzen', 'schockieren'],
  beruhigen: ['besänftigen', 'beschwichtigen', 'trösten', 'stillen'],
  aufregen: ['erregen', 'aufwühlen', 'erzürnen', 'empören'],
  langweilen: ['ermüden', 'einschläfern', 'anöden'],
  interessieren: ['fesseln', 'faszinieren', 'begeistern', 'ansprechen'],
  vergeben: ['verzeihen', 'entschuldigen', 'nachsehen', 'vergessen'],
  bereuen: ['bedauern', 'leidtun', 'grämen'],
  vertrauen: ['glauben', 'bauen auf', 'zählen auf', 'sich verlassen auf'],
  misstrauen: ['argwöhnen', 'bezweifeln', 'anzweifeln'],
  respektieren: ['achten', 'würdigen', 'schätzen', 'anerkennen'],
  verachten: ['geringschätzen', 'missachten', 'herabsehen'],
  bewundern: ['bestaunen', 'verehren', 'anhimmeln', 'schwärmen'],
  beneiden: ['neiden', 'missgönnen', 'eifersüchtig sein'],
  
  // === ERWEITERTE ADJEKTIVE ===
  wunderbar: ['fantastisch', 'herrlich', 'großartig', 'fabelhaft', 'prächtig', 'traumhaft'],
  schrecklich: ['furchtbar', 'entsetzlich', 'grauenhaft', 'fürchterlich', 'grässlich'],
  lustig: ['witzig', 'komisch', 'humorvoll', 'amüsant', 'ulkig', 'drollig', 'spaßig'],
  ernst: ['ernsthaft', 'seriös', 'feierlich', 'würdevoll', 'streng'],
  seltsam: ['merkwürdig', 'eigenartig', 'sonderbar', 'kurios', 'bizarr', 'skurril'],
  normal: ['gewöhnlich', 'üblich', 'durchschnittlich', 'alltäglich', 'regulär'],
  speziell: ['besonders', 'außergewöhnlich', 'einzigartig', 'exklusiv'],
  gewöhnlich: ['normal', 'üblich', 'alltäglich', 'banal', 'ordinär'],
  perfekt: ['ideal', 'makellos', 'vollendet', 'fehlerfrei', 'tadellos'],
  fehlerhaft: ['mangelhaft', 'defekt', 'kaputt', 'schadhaft'],
  möglich: ['machbar', 'realisierbar', 'denkbar', 'potentiell'],
  unmöglich: ['undurchführbar', 'unrealisierbar', 'ausgeschlossen'],
  nötig: ['notwendig', 'erforderlich', 'unerlässlich', 'obligatorisch'],
  unnötig: ['überflüssig', 'entbehrlich', 'verzichtbar'],
  sinnvoll: ['vernünftig', 'zweckmäßig', 'nutzbringend', 'praktisch'],
  sinnlos: ['zwecklos', 'nutzlos', 'vergeblich', 'unsinnig'],
  gerecht: ['fair', 'rechtmäßig', 'billig', 'angemessen'],
  ungerecht: ['unfair', 'parteiisch', 'einseitig', 'willkürlich'],
  ehrlich: ['aufrichtig', 'wahrhaftig', 'offen', 'redlich', 'integer'],
  unehrlich: ['verlogen', 'heuchlerisch', 'falsch', 'betrügerisch'],
  zuverlässig: ['verlässlich', 'vertrauenswürdig', 'beständig', 'solide'],
  unzuverlässig: ['wankelmütig', 'launisch', 'unberechenbar'],
  fleißig: ['emsig', 'arbeitsam', 'strebsam', 'tüchtig', 'rührig'],
  faul: ['träge', 'bequem', 'arbeitsscheu', 'müßig'],
  ordentlich: ['sauber', 'aufgeräumt', 'akkurat', 'korrekt'],
  unordentlich: ['chaotisch', 'schlampig', 'nachlässig', 'wirr'],
  vorsichtig: ['behutsam', 'achtsam', 'umsichtig', 'bedächtig'],
  leichtsinnig: ['unvorsichtig', 'fahrlässig', 'nachlässig', 'sorglos'],
  geduldig: ['langmütig', 'nachsichtig', 'beharrlich', 'gelassen'],
  ungeduldig: ['rastlos', 'nervös', 'hektisch', 'unruhig'],
  höflich: ['freundlich', 'zuvorkommend', 'respektvoll', 'artig'],
  unhöflich: ['grob', 'ungehobelt', 'barsch', 'schroff', 'rüde'],
  bescheiden: ['anspruchslos', 'genügsam', 'zurückhaltend', 'demütig'],
  arrogant: ['überheblich', 'eingebildet', 'hochnäsig', 'hochmütig', 'dünkelhaft'],
  neugierig: ['wissbegierig', 'interessiert', 'forschend', 'fragend'],
  gleichgültig: ['desinteressiert', 'teilnahmslos', 'apathisch', 'indifferent'],
  optimistisch: ['zuversichtlich', 'hoffnungsvoll', 'positiv', 'lebensfroh'],
  pessimistisch: ['negativ', 'schwarzseherisch', 'hoffnungslos', 'düster'],
  realistisch: ['sachlich', 'nüchtern', 'bodenständig', 'pragmatisch'],
  romantisch: ['verträumt', 'schwärmerisch', 'gefühlvoll', 'sentimental'],
  praktisch: ['nützlich', 'handlich', 'funktional', 'zweckmäßig'],
  theoretisch: ['abstrakt', 'hypothetisch', 'gedanklich'],
  oberflächlich: ['flüchtig', 'seicht', 'banal', 'trivial'],
  gründlich: ['sorgfältig', 'gewissenhaft', 'penibel', 'akribisch'],
  spontan: ['impulsiv', 'ungeplant', 'unüberlegt', 'aus dem Bauch'],
  überlegt: ['bedacht', 'durchdacht', 'wohlüberlegt', 'besonnen'],
  authentisch: ['echt', 'ungekünstelt', 'original', 'naturbelassen'],
  künstlich: ['synthetisch', 'unecht', 'nachgemacht', 'artifiziell'],
  komplex: ['kompliziert', 'vielschichtig', 'verwickelt', 'verschachtelt'],
  simpel: ['einfach', 'unkompliziert', 'schlicht', 'primitiv'],
  typisch: ['charakteristisch', 'bezeichnend', 'kennzeichnend', 'repräsentativ'],
  untypisch: ['ungewöhnlich', 'atypisch', 'uncharakteristisch'],
  aktuell: ['gegenwärtig', 'zeitgemäß', 'modern', 'heutig'],
  veraltet: ['antiquiert', 'überholt', 'altmodisch', 'obsolet'],
  bekannt: ['berühmt', 'populär', 'prominent', 'namhaft'],
  unbekannt: ['fremd', 'anonym', 'namenlos', 'unerforscht'],
  geheim: ['verborgen', 'heimlich', 'vertraulich', 'geheimnisvoll'],
  öffentlich: ['allgemein', 'publik', 'bekannt', 'offenkundig'],
  privat: ['persönlich', 'intim', 'individuell', 'eigen'],
  offiziell: ['amtlich', 'formell', 'förmlich', 'behördlich'],
  inoffiziell: ['informell', 'zwanglos', 'locker', 'ungezwungen'],
  
  // === ERWEITERTE SUBSTANTIVE ===
  Moment: ['Augenblick', 'Sekunde', 'Zeitpunkt', 'Instant'],
  Stunde: ['Zeitspanne', 'Weile', 'Periode'],
  Woche: ['Zeitraum', 'Sieben Tage'],
  Monat: ['Zeitabschnitt', 'Periode', 'Moon'],
  Zukunft: ['Morgen', 'Kommende', 'Perspektive'],
  Vergangenheit: ['Vorzeit', 'Geschichte', 'Früher'],
  Gegenwart: ['Jetzt', 'Heute', 'Aktualität'],
  Erinnerung: ['Gedächtnis', 'Andenken', 'Reminiszenz'],
  Wunsch: ['Begehren', 'Verlangen', 'Sehnsucht', 'Begehr'],
  Ziel: ['Zweck', 'Absicht', 'Bestimmung', 'Vorsatz'],
  Grund: ['Ursache', 'Anlass', 'Motiv', 'Beweggrund'],
  Folge: ['Konsequenz', 'Resultat', 'Auswirkung', 'Ergebnis'],
  Chance: ['Gelegenheit', 'Möglichkeit', 'Option', 'Aussicht'],
  Gefahr: ['Risiko', 'Bedrohung', 'Wagnis', 'Bedrängnis'],
  Hilfe: ['Unterstützung', 'Beistand', 'Assistenz', 'Förderung'],
  Rat: ['Empfehlung', 'Tipp', 'Hinweis', 'Vorschlag'],
  Fehler: ['Irrtum', 'Versehen', 'Patzer', 'Schnitzer', 'Fauxpas'],
  Gelingen: ['Triumph', 'Sieg', 'Errungenschaft', 'Durchbruch'],
  Niederlage: ['Misserfolg', 'Scheitern', 'Fiasko', 'Pleite'],
  Arbeit: ['Tätigkeit', 'Beschäftigung', 'Beruf', 'Job', 'Werk'],
  Ruhe: ['Stille', 'Frieden', 'Gelassenheit', 'Entspannung'],
  Lärm: ['Krach', 'Getöse', 'Radau', 'Tumult'],
  Ordnung: ['Struktur', 'System', 'Regelung', 'Organisation'],
  Chaos: ['Durcheinander', 'Wirrwarr', 'Tohuwabohu', 'Unordnung'],
  Anfang: ['Beginn', 'Start', 'Auftakt', 'Ursprung'],
  Ende: ['Schluss', 'Abschluss', 'Finale', 'Ausgang'],
  Mitte: ['Zentrum', 'Kern', 'Herz', 'Mittelpunkt'],
  Rand: ['Kante', 'Saum', 'Grenze', 'Peripherie'],
  Oberfläche: ['Außenseite', 'Fläche', 'Hülle'],
  Tiefe: ['Abgrund', 'Grund', 'Inneres'],
  Höhe: ['Gipfel', 'Spitze', 'Niveau', 'Pegel'],
  Breite: ['Weite', 'Ausdehnung', 'Umfang'],
  Länge: ['Strecke', 'Distanz', 'Ausdehnung'],
  Größe: ['Ausmaß', 'Umfang', 'Dimension', 'Format'],
  Form: ['Gestalt', 'Figur', 'Kontur', 'Umriss'],
  Farbe: ['Kolorit', 'Ton', 'Nuance', 'Schattierung'],
  Licht: ['Helligkeit', 'Schein', 'Glanz', 'Strahlung'],
  Schatten: ['Dunkelheit', 'Finsternis', 'Dämmerlicht'],
  Geruch: ['Duft', 'Aroma', 'Gestank', 'Wohlgeruch'],
  Geschmack: ['Aroma', 'Würze', 'Geschmacksrichtung'],
  Empfindung: ['Gefühl', 'Emotion', 'Regung', 'Stimmung'],
  Einfall: ['Gedanke', 'Idee', 'Überlegung', 'Vorstellung'],
  Meinung: ['Ansicht', 'Standpunkt', 'Auffassung', 'Position'],
  Wissen: ['Kenntnis', 'Erkenntnis', 'Bildung', 'Know-how'],
  Können: ['Fähigkeit', 'Fertigkeit', 'Talent', 'Geschick'],
  Erfahrung: ['Praxis', 'Routine', 'Expertise', 'Sachkenntnis'],
  Beispiel: ['Muster', 'Vorbild', 'Modell', 'Paradigma'],
  Beweis: ['Nachweis', 'Beleg', 'Evidenz', 'Zeugnis'],
  Zeichen: ['Symbol', 'Signal', 'Indiz', 'Hinweis'],
  Bild: ['Gemälde', 'Foto', 'Abbildung', 'Darstellung'],
  Text: ['Schrift', 'Dokument', 'Passage', 'Abschnitt'],
  Begriff: ['Wort', 'Ausdruck', 'Vokabel', 'Terminus'],
  Satz: ['Aussage', 'Statement', 'Phrase'],
  Sprache: ['Zunge', 'Idiom', 'Mundart', 'Dialekt'],
  Stimme: ['Tonfall', 'Klang', 'Organ', 'Stimmlage'],
  Musik: ['Melodie', 'Klänge', 'Harmonien', 'Töne'],
  Kunst: ['Kunstwerk', 'Kreation', 'Schöpfung'],
  Natur: ['Umwelt', 'Schöpfung', 'Wildnis', 'Ökosystem'],
  Welt: ['Erde', 'Globus', 'Kosmos', 'Universum'],
  Firmament: ['Himmel', 'Äther', 'Wolken', 'Paradies'],
  Boden: ['Erde', 'Grund', 'Terrain', 'Planet'],
  Luft: ['Atmosphäre', 'Odem', 'Hauch', 'Wind'],
  Nass: ['Wasser', 'Flüssigkeit', 'Quelle', 'Element'],
  Flamme: ['Feuer', 'Brand', 'Lohe', 'Glut', 'Inferno'],
  Sturm: ['Unwetter', 'Orkan', 'Gewitter', 'Tornado'],
  Blitz: ['Wetterleuchten', 'Donnerkeil', 'Strahl'],
  Donner: ['Grollen', 'Krachen', 'Getöse'],
  Wolke: ['Gewölk', 'Nebel', 'Dunst', 'Schleier'],
  Nebel: ['Dunst', 'Schleier', 'Dampf', 'Brodel'],
  Frost: ['Kälte', 'Eis', 'Reif', 'Winter'],
  Hitze: ['Wärme', 'Glut', 'Schwüle', 'Sommerhitze'],
  Gesicht: ['Antlitz', 'Miene', 'Visage', 'Angesicht'],
  Auge: ['Blick', 'Sehorgan', 'Pupille'],
  Ohr: ['Gehör', 'Lauscher', 'Hörorgan'],
  Nase: ['Riecher', 'Zinken', 'Geruchsorgan'],
  Mund: ['Lippen', 'Schnabel', 'Maul', 'Mundwerk'],
  Hand: ['Pranke', 'Flosse', 'Greifer', 'Pfote'],
  Fuß: ['Treter', 'Quadratlatschen', 'Gehwerkzeug'],
  Kopf: ['Haupt', 'Schädel', 'Birne', 'Oberstübchen'],
  Körper: ['Leib', 'Gestalt', 'Figur', 'Physik'],
  Psyche: ['Geist', 'Seele', 'Inneres', 'Gemüt'],
  Intellekt: ['Geist', 'Verstand', 'Bewusstsein', 'Ratio'],
  Innerstes: ['Herz', 'Seele', 'Gemüt', 'Kern'],
  Blut: ['Lebenssaft', 'Geblüt', 'Saft'],
  Träne: ['Zähre', 'Tropfen', 'Freudenträne'],
  Lächeln: ['Schmunzeln', 'Grinsen', 'Strahlen'],
  Schrei: ['Ruf', 'Aufschrei', 'Gebrüll', 'Geschrei'],
  Geflüster: ['Wispern', 'Raunen', 'Gemurmel'],
  Schritt: ['Gang', 'Tritt', 'Bewegung', 'Stufe'],
  Sprung: ['Satz', 'Hüpfer', 'Hopser', 'Hechtsprung'],
  Griff: ['Handgriff', 'Zugriff', 'Fassung', 'Halt'],
  Schlag: ['Hieb', 'Stoß', 'Treffer', 'Klaps'],
  Kuss: ['Busserl', 'Schmatz', 'Schnabel'],
  Umarmung: ['Umschlingung', 'Drücker', 'Liebkosung'],
  Ausblick: ['Anblick', 'Sicht', 'Ausschau', 'Perspektive']
};

// Case-insensitive lookup Map
const synonymLookup = new Map<string, string[]>();

for (const [word, synonyms] of Object.entries(SYNONYM_MAP)) {
  synonymLookup.set(word.toLowerCase(), synonyms);
}

// Import English synonyms
import { findEnglishSynonyms, hasEnglishSynonyms, getEnglishSynonymCount } from './synonyms-en';

export function hasSynonyms(word: string, lang: 'de' | 'en' = 'de'): boolean {
  if (lang === 'en') {
    return hasEnglishSynonyms(word);
  }
  return synonymLookup.has(word.toLowerCase());
}

export function findLocalSynonyms(word: string, lang: 'de' | 'en' = 'de'): string[] {
  if (lang === 'en') {
    return findEnglishSynonyms(word);
  }
  return synonymLookup.get(word.toLowerCase()) || [];
}

export function getSynonymCount(lang: 'de' | 'en' = 'de'): number {
  if (lang === 'en') {
    return getEnglishSynonymCount();
  }
  return synonymLookup.size;
}
