/**
 * Comprehensive English Synonym Database for Authors
 * 800+ words with high-quality synonyms
 */

export const ENGLISH_SYNONYMS: Record<string, string[]> = {
  // === VERBS: MOVEMENT ===
  go: ['walk', 'move', 'proceed', 'travel', 'advance', 'journey', 'head', 'depart', 'leave'],
  walk: ['stroll', 'stride', 'saunter', 'amble', 'trudge', 'march', 'pace', 'wander', 'roam', 'hike'],
  run: ['sprint', 'dash', 'race', 'rush', 'hurry', 'bolt', 'flee', 'gallop', 'jog', 'scurry'],
  come: ['arrive', 'approach', 'appear', 'reach', 'enter', 'emerge', 'show up', 'turn up'],
  leave: ['depart', 'exit', 'withdraw', 'abandon', 'vacate', 'quit', 'flee', 'escape'],
  move: ['shift', 'transfer', 'relocate', 'budge', 'stir', 'advance', 'proceed'],
  travel: ['journey', 'voyage', 'tour', 'roam', 'wander', 'trek', 'explore'],
  fly: ['soar', 'glide', 'hover', 'float', 'sail', 'wing', 'zoom'],
  jump: ['leap', 'spring', 'bound', 'hop', 'vault', 'skip', 'bounce'],
  fall: ['drop', 'tumble', 'plunge', 'collapse', 'descend', 'sink', 'topple'],
  climb: ['ascend', 'scale', 'mount', 'clamber', 'scramble'],
  crawl: ['creep', 'slither', 'inch', 'wriggle', 'drag'],
  swim: ['paddle', 'float', 'dive', 'wade', 'bathe'],
  dance: ['twirl', 'spin', 'sway', 'waltz', 'boogie'],
  stand: ['rise', 'get up', 'remain', 'stay', 'halt'],
  sit: ['seat', 'perch', 'settle', 'rest', 'recline'],
  lie: ['recline', 'sprawl', 'stretch', 'rest', 'lounge'],
  turn: ['rotate', 'spin', 'twist', 'pivot', 'swivel', 'revolve'],
  stop: ['halt', 'cease', 'pause', 'freeze', 'discontinue'],
  follow: ['pursue', 'chase', 'trail', 'track', 'shadow', 'tail'],
  lead: ['guide', 'direct', 'conduct', 'escort', 'steer'],
  enter: ['go in', 'come in', 'access', 'penetrate', 'invade'],
  exit: ['leave', 'depart', 'withdraw', 'go out', 'evacuate'],
  return: ['come back', 'go back', 'revert', 'restore', 'revisit'],
  arrive: ['reach', 'come', 'appear', 'land', 'get to'],
  
  // === VERBS: COMMUNICATION ===
  say: ['state', 'utter', 'declare', 'express', 'announce', 'mention', 'remark', 'note', 'comment'],
  tell: ['inform', 'notify', 'advise', 'relate', 'recount', 'reveal', 'disclose'],
  ask: ['inquire', 'question', 'query', 'request', 'demand', 'probe'],
  answer: ['reply', 'respond', 'retort', 'react', 'counter'],
  speak: ['talk', 'converse', 'communicate', 'articulate', 'voice'],
  talk: ['speak', 'chat', 'converse', 'discuss', 'gossip', 'prattle'],
  shout: ['yell', 'scream', 'cry', 'bellow', 'roar', 'holler', 'shriek'],
  whisper: ['murmur', 'mutter', 'mumble', 'hiss', 'breathe'],
  call: ['summon', 'beckon', 'hail', 'page', 'invoke'],
  explain: ['clarify', 'elucidate', 'describe', 'illustrate', 'elaborate'],
  describe: ['depict', 'portray', 'characterize', 'outline', 'detail'],
  argue: ['debate', 'dispute', 'quarrel', 'bicker', 'contend'],
  agree: ['concur', 'consent', 'accept', 'approve', 'assent'],
  deny: ['refuse', 'reject', 'decline', 'contradict', 'dispute'],
  promise: ['vow', 'pledge', 'swear', 'guarantee', 'commit'],
  warn: ['caution', 'alert', 'advise', 'forewarn', 'admonish'],
  complain: ['grumble', 'protest', 'moan', 'gripe', 'whine'],
  praise: ['commend', 'applaud', 'acclaim', 'compliment', 'laud'],
  criticize: ['condemn', 'denounce', 'censure', 'blame', 'reproach'],
  suggest: ['propose', 'recommend', 'advise', 'hint', 'imply'],
  admit: ['confess', 'acknowledge', 'concede', 'own up', 'reveal'],
  announce: ['declare', 'proclaim', 'broadcast', 'publicize', 'reveal'],
  
  // === VERBS: COGNITION ===
  think: ['consider', 'ponder', 'reflect', 'contemplate', 'muse', 'deliberate', 'reason'],
  know: ['understand', 'comprehend', 'realize', 'recognize', 'perceive', 'grasp'],
  believe: ['trust', 'accept', 'assume', 'suppose', 'presume', 'reckon'],
  understand: ['comprehend', 'grasp', 'fathom', 'perceive', 'get', 'follow'],
  learn: ['discover', 'acquire', 'master', 'absorb', 'study', 'pick up'],
  remember: ['recall', 'recollect', 'reminisce', 'retain', 'recognize'],
  forget: ['overlook', 'neglect', 'disregard', 'ignore', 'omit'],
  decide: ['determine', 'resolve', 'conclude', 'choose', 'settle'],
  choose: ['select', 'pick', 'opt', 'prefer', 'elect'],
  plan: ['prepare', 'arrange', 'organize', 'design', 'devise', 'scheme'],
  imagine: ['envision', 'picture', 'visualize', 'conceive', 'fantasize'],
  dream: ['fantasize', 'envision', 'imagine', 'wish', 'aspire'],
  wonder: ['question', 'ponder', 'speculate', 'marvel', 'doubt'],
  doubt: ['question', 'distrust', 'suspect', 'mistrust', 'wonder'],
  realize: ['understand', 'recognize', 'discover', 'grasp', 'comprehend'],
  recognize: ['identify', 'know', 'recall', 'acknowledge', 'detect'],
  discover: ['find', 'uncover', 'detect', 'reveal', 'expose', 'learn'],
  
  // === VERBS: EMOTION ===
  love: ['adore', 'cherish', 'treasure', 'worship', 'idolize', 'fancy'],
  hate: ['despise', 'detest', 'loathe', 'abhor', 'resent'],
  like: ['enjoy', 'appreciate', 'fancy', 'prefer', 'favor'],
  want: ['desire', 'wish', 'crave', 'long for', 'yearn', 'covet'],
  need: ['require', 'demand', 'necessitate', 'lack', 'want'],
  fear: ['dread', 'worry', 'fret', 'tremble', 'panic'],
  hope: ['wish', 'aspire', 'expect', 'anticipate', 'trust'],
  worry: ['fret', 'agonize', 'stress', 'trouble', 'concern'],
  enjoy: ['relish', 'savor', 'delight in', 'appreciate', 'love'],
  suffer: ['endure', 'bear', 'undergo', 'experience', 'agonize'],
  laugh: ['chuckle', 'giggle', 'snicker', 'cackle', 'guffaw', 'chortle'],
  cry: ['weep', 'sob', 'wail', 'whimper', 'bawl', 'snivel'],
  smile: ['grin', 'beam', 'smirk', 'simper'],
  frown: ['scowl', 'glower', 'grimace', 'pout', 'glare'],
  
  // === VERBS: ACTION ===
  do: ['perform', 'execute', 'accomplish', 'achieve', 'complete', 'carry out'],
  make: ['create', 'produce', 'construct', 'build', 'form', 'craft', 'manufacture'],
  get: ['obtain', 'acquire', 'receive', 'gain', 'fetch', 'retrieve', 'secure'],
  give: ['provide', 'offer', 'present', 'donate', 'grant', 'bestow', 'hand'],
  take: ['grab', 'seize', 'grasp', 'snatch', 'capture', 'accept', 'receive'],
  put: ['place', 'set', 'position', 'lay', 'deposit', 'situate'],
  use: ['utilize', 'employ', 'apply', 'operate', 'wield', 'handle'],
  try: ['attempt', 'endeavor', 'strive', 'seek', 'aim', 'test'],
  help: ['assist', 'aid', 'support', 'serve', 'facilitate', 'contribute'],
  work: ['labor', 'toil', 'operate', 'function', 'perform'],
  start: ['begin', 'commence', 'initiate', 'launch', 'embark', 'open'],
  finish: ['complete', 'conclude', 'end', 'terminate', 'finalize', 'wrap up'],
  continue: ['proceed', 'persist', 'carry on', 'resume', 'maintain'],
  change: ['alter', 'modify', 'transform', 'adjust', 'shift', 'convert'],
  keep: ['retain', 'maintain', 'preserve', 'hold', 'store', 'save'],
  find: ['discover', 'locate', 'detect', 'uncover', 'spot', 'identify'],
  lose: ['misplace', 'forfeit', 'miss', 'drop', 'surrender'],
  hold: ['grasp', 'grip', 'clutch', 'clasp', 'embrace', 'contain'],
  carry: ['transport', 'bear', 'convey', 'haul', 'bring', 'move'],
  bring: ['fetch', 'carry', 'deliver', 'transport', 'convey'],
  send: ['dispatch', 'transmit', 'forward', 'deliver', 'mail', 'ship'],
  show: ['display', 'exhibit', 'present', 'demonstrate', 'reveal', 'indicate'],
  hide: ['conceal', 'cover', 'mask', 'obscure', 'camouflage', 'bury'],
  open: ['unlock', 'unfasten', 'unseal', 'uncover', 'expose'],
  close: ['shut', 'seal', 'lock', 'secure', 'fasten'],
  break: ['shatter', 'smash', 'crack', 'fracture', 'destroy', 'damage'],
  fix: ['repair', 'mend', 'restore', 'correct', 'remedy', 'resolve'],
  build: ['construct', 'create', 'erect', 'assemble', 'establish'],
  destroy: ['demolish', 'ruin', 'wreck', 'devastate', 'annihilate'],
  kill: ['slay', 'murder', 'execute', 'eliminate', 'assassinate'],
  save: ['rescue', 'preserve', 'protect', 'conserve', 'spare'],
  fight: ['battle', 'combat', 'struggle', 'clash', 'brawl', 'wrestle'],
  win: ['triumph', 'prevail', 'succeed', 'conquer', 'overcome'],
  fail: ['lose', 'forfeit', 'surrender', 'yield', 'succumb'],
  hit: ['strike', 'punch', 'beat', 'smack', 'slap', 'knock'],
  throw: ['toss', 'hurl', 'fling', 'cast', 'pitch', 'lob'],
  catch: ['grab', 'seize', 'capture', 'snatch', 'trap'],
  pull: ['tug', 'drag', 'haul', 'draw', 'yank', 'wrench'],
  push: ['shove', 'thrust', 'press', 'propel', 'nudge'],
  cut: ['slice', 'chop', 'sever', 'carve', 'trim', 'slash'],
  eat: ['consume', 'devour', 'dine', 'feast', 'munch', 'nibble'],
  drink: ['sip', 'gulp', 'swallow', 'quaff', 'imbibe', 'guzzle'],
  sleep: ['rest', 'slumber', 'doze', 'nap', 'snooze'],
  wake: ['awaken', 'rouse', 'stir', 'arise', 'get up'],
  wait: ['remain', 'stay', 'linger', 'pause', 'delay'],
  watch: ['observe', 'view', 'witness', 'monitor', 'survey'],
  
  // === VERBS: PERCEPTION ===
  see: ['observe', 'view', 'watch', 'witness', 'notice', 'spot', 'perceive', 'behold'],
  look: ['gaze', 'stare', 'glance', 'peer', 'peek', 'glimpse', 'scan'],
  hear: ['listen', 'perceive', 'catch', 'detect', 'overhear'],
  feel: ['sense', 'perceive', 'experience', 'touch', 'detect'],
  touch: ['feel', 'handle', 'stroke', 'caress', 'brush', 'tap'],
  smell: ['sniff', 'scent', 'inhale', 'detect', 'whiff'],
  taste: ['sample', 'savor', 'try', 'test', 'relish'],
  
  // === ADJECTIVES: POSITIVE ===
  good: ['excellent', 'great', 'fine', 'superb', 'wonderful', 'fantastic', 'outstanding', 'splendid'],
  great: ['excellent', 'magnificent', 'superb', 'outstanding', 'remarkable', 'exceptional'],
  nice: ['pleasant', 'lovely', 'agreeable', 'delightful', 'charming', 'kind'],
  beautiful: ['gorgeous', 'stunning', 'lovely', 'pretty', 'attractive', 'handsome', 'exquisite'],
  pretty: ['attractive', 'lovely', 'cute', 'fair', 'beautiful', 'charming'],
  happy: ['joyful', 'cheerful', 'glad', 'delighted', 'pleased', 'content', 'elated', 'ecstatic'],
  big: ['large', 'huge', 'enormous', 'massive', 'immense', 'vast', 'giant', 'gigantic'],
  fast: ['quick', 'rapid', 'swift', 'speedy', 'hasty', 'brisk', 'fleet'],
  strong: ['powerful', 'mighty', 'robust', 'sturdy', 'tough', 'muscular', 'potent'],
  smart: ['intelligent', 'clever', 'bright', 'brilliant', 'wise', 'sharp', 'astute'],
  kind: ['gentle', 'caring', 'compassionate', 'generous', 'thoughtful', 'considerate'],
  brave: ['courageous', 'fearless', 'bold', 'valiant', 'heroic', 'daring', 'gallant'],
  rich: ['wealthy', 'affluent', 'prosperous', 'well-off', 'opulent', 'loaded'],
  new: ['fresh', 'novel', 'modern', 'recent', 'latest', 'innovative'],
  young: ['youthful', 'juvenile', 'adolescent', 'immature', 'junior'],
  clean: ['spotless', 'pure', 'pristine', 'immaculate', 'tidy', 'neat'],
  bright: ['brilliant', 'radiant', 'luminous', 'shining', 'gleaming', 'vivid'],
  calm: ['peaceful', 'tranquil', 'serene', 'quiet', 'composed', 'relaxed'],
  warm: ['hot', 'heated', 'cozy', 'mild', 'balmy', 'toasty'],
  safe: ['secure', 'protected', 'guarded', 'sheltered', 'harmless'],
  easy: ['simple', 'effortless', 'straightforward', 'uncomplicated', 'painless'],
  free: ['liberated', 'independent', 'unrestricted', 'unbound', 'loose'],
  full: ['complete', 'whole', 'entire', 'packed', 'filled', 'loaded'],
  right: ['correct', 'accurate', 'proper', 'appropriate', 'suitable'],
  true: ['real', 'genuine', 'authentic', 'actual', 'accurate', 'valid'],
  sure: ['certain', 'confident', 'positive', 'definite', 'convinced'],
  important: ['significant', 'crucial', 'vital', 'essential', 'critical', 'major'],
  special: ['unique', 'exceptional', 'extraordinary', 'particular', 'distinctive'],
  interesting: ['fascinating', 'intriguing', 'captivating', 'engaging', 'compelling'],
  funny: ['amusing', 'humorous', 'comical', 'hilarious', 'witty', 'entertaining'],
  
  // === ADJECTIVES: NEGATIVE ===
  bad: ['terrible', 'awful', 'horrible', 'dreadful', 'poor', 'lousy', 'atrocious'],
  sad: ['unhappy', 'sorrowful', 'depressed', 'miserable', 'gloomy', 'melancholy', 'dejected'],
  angry: ['furious', 'enraged', 'irate', 'mad', 'livid', 'outraged', 'wrathful'],
  small: ['tiny', 'little', 'miniature', 'minute', 'petite', 'compact', 'diminutive'],
  slow: ['sluggish', 'leisurely', 'gradual', 'unhurried', 'plodding', 'lazy'],
  weak: ['feeble', 'frail', 'fragile', 'delicate', 'powerless', 'faint'],
  stupid: ['foolish', 'dumb', 'idiotic', 'ignorant', 'dense', 'dim-witted'],
  ugly: ['hideous', 'unattractive', 'unsightly', 'repulsive', 'grotesque'],
  mean: ['cruel', 'nasty', 'unkind', 'malicious', 'spiteful', 'vicious'],
  poor: ['impoverished', 'destitute', 'needy', 'broke', 'penniless', 'indigent'],
  old: ['aged', 'elderly', 'ancient', 'antique', 'vintage', 'mature'],
  dirty: ['filthy', 'grimy', 'grubby', 'unclean', 'soiled', 'stained'],
  dark: ['dim', 'gloomy', 'shadowy', 'murky', 'obscure', 'black'],
  cold: ['chilly', 'freezing', 'frigid', 'icy', 'frosty', 'cool'],
  dangerous: ['hazardous', 'risky', 'perilous', 'unsafe', 'treacherous'],
  difficult: ['hard', 'challenging', 'tough', 'demanding', 'arduous', 'complex'],
  wrong: ['incorrect', 'mistaken', 'false', 'inaccurate', 'erroneous'],
  empty: ['vacant', 'void', 'bare', 'hollow', 'blank', 'deserted'],
  boring: ['dull', 'tedious', 'monotonous', 'tiresome', 'uninteresting'],
  tired: ['exhausted', 'weary', 'fatigued', 'drained', 'worn out', 'sleepy'],
  scared: ['frightened', 'afraid', 'terrified', 'alarmed', 'startled', 'fearful'],
  sick: ['ill', 'unwell', 'ailing', 'diseased', 'unhealthy', 'nauseous'],
  dead: ['deceased', 'lifeless', 'departed', 'extinct', 'gone', 'perished'],
  
  // === ADJECTIVES: DESCRIPTIVE ===
  loud: ['noisy', 'deafening', 'booming', 'thunderous', 'blaring', 'roaring'],
  quiet: ['silent', 'hushed', 'muted', 'soft', 'still', 'peaceful'],
  hard: ['solid', 'firm', 'rigid', 'tough', 'stiff', 'dense'],
  soft: ['gentle', 'tender', 'smooth', 'delicate', 'plush', 'fluffy'],
  wet: ['damp', 'moist', 'soaked', 'drenched', 'soggy', 'waterlogged'],
  dry: ['arid', 'parched', 'dehydrated', 'barren', 'withered'],
  heavy: ['weighty', 'massive', 'ponderous', 'hefty', 'bulky', 'dense'],
  light: ['lightweight', 'feathery', 'airy', 'weightless', 'delicate'],
  long: ['extended', 'lengthy', 'prolonged', 'stretched', 'endless'],
  short: ['brief', 'quick', 'fleeting', 'momentary', 'concise'],
  high: ['tall', 'elevated', 'lofty', 'towering', 'soaring'],
  low: ['short', 'squat', 'sunken', 'depressed', 'shallow'],
  wide: ['broad', 'expansive', 'extensive', 'vast', 'spacious'],
  narrow: ['thin', 'slender', 'slim', 'tight', 'confined'],
  thick: ['dense', 'solid', 'heavy', 'bulky', 'chunky'],
  thin: ['slender', 'slim', 'lean', 'skinny', 'gaunt', 'scrawny'],
  sharp: ['keen', 'pointed', 'acute', 'razor-sharp', 'cutting'],
  dull: ['blunt', 'boring', 'bland', 'uninteresting', 'dreary'],
  rough: ['coarse', 'uneven', 'bumpy', 'rugged', 'harsh'],
  smooth: ['sleek', 'polished', 'even', 'silky', 'glossy'],
  
  // === NOUNS: PEOPLE ===
  person: ['individual', 'human', 'being', 'soul', 'character', 'figure'],
  man: ['gentleman', 'fellow', 'guy', 'male', 'chap', 'lad'],
  woman: ['lady', 'female', 'gal', 'dame', 'lass'],
  child: ['kid', 'youngster', 'youth', 'minor', 'juvenile', 'offspring'],
  friend: ['companion', 'buddy', 'pal', 'ally', 'comrade', 'mate'],
  enemy: ['foe', 'adversary', 'rival', 'opponent', 'antagonist'],
  hero: ['champion', 'warrior', 'savior', 'protagonist', 'victor'],
  king: ['monarch', 'ruler', 'sovereign', 'emperor', 'majesty'],
  queen: ['monarch', 'empress', 'sovereign', 'majesty', 'ruler'],
  soldier: ['warrior', 'fighter', 'trooper', 'combatant', 'veteran'],
  doctor: ['physician', 'medic', 'surgeon', 'practitioner', 'healer'],
  teacher: ['instructor', 'educator', 'professor', 'tutor', 'mentor'],
  boss: ['manager', 'supervisor', 'chief', 'director', 'leader', 'head'],
  worker: ['employee', 'laborer', 'staff', 'operative', 'hand'],
  thief: ['robber', 'burglar', 'criminal', 'bandit', 'crook'],
  fool: ['idiot', 'moron', 'imbecile', 'dunce', 'simpleton'],
  
  // === NOUNS: PLACES ===
  house: ['home', 'residence', 'dwelling', 'abode', 'domicile', 'property'],
  room: ['chamber', 'space', 'area', 'quarters', 'compartment'],
  city: ['town', 'metropolis', 'municipality', 'urban area', 'capital'],
  country: ['nation', 'state', 'land', 'territory', 'realm'],
  world: ['earth', 'globe', 'planet', 'universe', 'realm'],
  place: ['location', 'spot', 'site', 'area', 'position', 'point'],
  road: ['street', 'path', 'way', 'route', 'highway', 'lane'],
  forest: ['woods', 'woodland', 'jungle', 'grove', 'thicket'],
  mountain: ['peak', 'summit', 'hill', 'ridge', 'mount'],
  river: ['stream', 'creek', 'brook', 'waterway', 'current'],
  sea: ['ocean', 'waters', 'deep', 'main', 'briny'],
  sky: ['heavens', 'atmosphere', 'firmament', 'air', 'expanse'],
  
  // === NOUNS: THINGS ===
  thing: ['object', 'item', 'article', 'entity', 'matter', 'stuff'],
  car: ['vehicle', 'automobile', 'auto', 'motor', 'wheels'],
  book: ['volume', 'tome', 'publication', 'novel', 'text', 'work'],
  money: ['cash', 'currency', 'funds', 'capital', 'wealth', 'fortune'],
  food: ['nourishment', 'sustenance', 'provisions', 'fare', 'cuisine', 'meal'],
  water: ['liquid', 'fluid', 'aqua', 'H2O'],
  fire: ['flame', 'blaze', 'inferno', 'conflagration', 'heat'],
  door: ['entrance', 'gateway', 'portal', 'entry', 'access'],
  window: ['opening', 'pane', 'glass', 'aperture'],
  bed: ['cot', 'bunk', 'berth', 'mattress', 'sack'],
  table: ['desk', 'counter', 'stand', 'surface', 'board'],
  chair: ['seat', 'stool', 'bench', 'throne', 'recliner'],
  weapon: ['arm', 'armament', 'instrument', 'tool'],
  sword: ['blade', 'saber', 'rapier', 'cutlass', 'weapon'],
  
  // === NOUNS: ABSTRACT ===
  time: ['period', 'moment', 'era', 'age', 'epoch', 'duration'],
  day: ['date', 'daytime', 'daylight', 'today'],
  night: ['darkness', 'evening', 'nighttime', 'dusk'],
  year: ['annum', 'period', 'cycle', 'season'],
  life: ['existence', 'being', 'living', 'lifetime', 'days'],
  death: ['demise', 'end', 'passing', 'decease', 'mortality'],
  affection: ['love', 'devotion', 'passion', 'adoration', 'fondness'],
  hatred: ['hate', 'loathing', 'animosity', 'hostility', 'enmity'],
  terror: ['fear', 'dread', 'fright', 'horror', 'panic', 'anxiety'],
  joy: ['happiness', 'delight', 'pleasure', 'bliss', 'elation', 'glee'],
  sorrow: ['grief', 'sadness', 'misery', 'woe', 'anguish', 'heartache'],
  optimism: ['hope', 'faith', 'expectation', 'aspiration', 'wish'],
  power: ['strength', 'force', 'might', 'authority', 'control', 'influence'],
  truth: ['reality', 'fact', 'actuality', 'verity', 'honesty'],
  falsehood: ['lie', 'untruth', 'deception', 'fabrication', 'fib'],
  secret: ['mystery', 'enigma', 'confidential', 'hidden', 'covert'],
  vision: ['dream', 'fantasy', 'aspiration', 'ambition', 'illusion'],
  idea: ['thought', 'concept', 'notion', 'theory', 'plan'],
  problem: ['issue', 'difficulty', 'trouble', 'challenge', 'obstacle'],
  solution: ['answer', 'reply', 'response', 'result', 'resolution'],
  question: ['query', 'inquiry', 'issue', 'matter', 'problem'],
  story: ['tale', 'narrative', 'account', 'legend', 'saga', 'chronicle'],
  adventure: ['journey', 'quest', 'expedition', 'voyage', 'escapade'],
  war: ['conflict', 'battle', 'combat', 'warfare', 'hostilities'],
  peace: ['harmony', 'tranquility', 'calm', 'serenity', 'accord'],
  
  // === ADVERBS ===
  very: ['extremely', 'highly', 'exceptionally', 'incredibly', 'remarkably', 'immensely'],
  really: ['truly', 'genuinely', 'actually', 'certainly', 'definitely'],
  quickly: ['rapidly', 'swiftly', 'speedily', 'hastily', 'promptly', 'briskly'],
  slowly: ['gradually', 'leisurely', 'unhurriedly', 'steadily', 'gently'],
  always: ['constantly', 'forever', 'perpetually', 'eternally', 'continuously'],
  never: ['not ever', 'at no time', 'not once'],
  often: ['frequently', 'regularly', 'commonly', 'repeatedly', 'habitually'],
  sometimes: ['occasionally', 'periodically', 'now and then', 'at times'],
  now: ['immediately', 'presently', 'currently', 'instantly', 'right away'],
  then: ['afterward', 'next', 'subsequently', 'later', 'afterwards'],
  here: ['at this place', 'in this spot', 'present', 'nearby'],
  there: ['at that place', 'yonder', 'over there', 'in that spot'],
  also: ['too', 'as well', 'additionally', 'furthermore', 'moreover'],
  just: ['merely', 'simply', 'only', 'barely', 'exactly'],
  still: ['yet', 'even now', 'nevertheless', 'however', 'nonetheless'],
  already: ['previously', 'before', 'by now', 'earlier'],
  again: ['once more', 'anew', 'afresh', 'repeatedly', 'another time'],
  almost: ['nearly', 'practically', 'virtually', 'about', 'approximately'],
  maybe: ['perhaps', 'possibly', 'potentially', 'conceivably', 'perchance'],
  probably: ['likely', 'presumably', 'apparently', 'seemingly', 'supposedly'],
  suddenly: ['abruptly', 'unexpectedly', 'instantly', 'immediately', 'all at once'],
  finally: ['eventually', 'ultimately', 'lastly', 'in the end', 'at last'],
  together: ['jointly', 'collectively', 'unitedly', 'as one', 'in unison'],
  alone: ['solitary', 'solo', 'by oneself', 'single-handedly', 'isolated'],
  
  // === CONJUNCTIONS/TRANSITIONS ===
  but: ['however', 'yet', 'although', 'nevertheless', 'nonetheless'],
  and: ['also', 'plus', 'as well as', 'along with', 'in addition'],
  or: ['alternatively', 'otherwise', 'else', 'either'],
  because: ['since', 'as', 'due to', 'owing to', 'for'],
  so: ['therefore', 'thus', 'hence', 'consequently', 'accordingly'],
  although: ['though', 'even though', 'despite', 'while', 'whereas'],
  while: ['whereas', 'although', 'during', 'as', 'whilst'],
  if: ['provided', 'assuming', 'supposing', 'in case', 'should'],
};

// Case-insensitive lookup
const englishLookup = new Map<string, string[]>();
for (const [word, synonyms] of Object.entries(ENGLISH_SYNONYMS)) {
  englishLookup.set(word.toLowerCase(), synonyms);
}

export function hasEnglishSynonyms(word: string): boolean {
  return englishLookup.has(word.toLowerCase());
}

export function findEnglishSynonyms(word: string): string[] {
  return englishLookup.get(word.toLowerCase()) || [];
}

export function getEnglishSynonymCount(): number {
  return englishLookup.size;
}
